
(defun shdennlin/temp ()
  (interactive)
  (save-buffer)
  (run-with-timer .1 nil 'spacemacs/python-execute-file t)
  (run-with-timer .1 nil 'execute-kbd-macro (kbd "C-a"))
  (run-with-timer .1 nil 'execute-kbd-macro (kbd "C-k"))
  (run-with-timer .1 nil 'insert "/home/shdennlin/anaconda3/bin/ipython main.py")
  (run-with-timer .1 nil 'execute-kbd-macro (kbd "RET"))
  (run-with-timer .1 nil 'execute-kbd-macro (kbd "<escape>"))
  )


(defun shdennlin/temp ()
  (interactive)
  (save-buffer)
  (spacemacs/persp-switch-to-3)
  (run-with-timer .1 nil 'spacemacs/python-execute-file "~/work/ball/court-babayka/main.py")
  (run-with-timer .1 nil 'execute-kbd-macro (kbd "RET"))
  (run-with-timer .1 nil 'execute-kbd-macro (kbd "<escape>"))
  )

(global-set-key (kbd "<f5>") 'shdennlin/temp)

(defun shdennlin/str ()
  (interactive)
  (copy-region-as-kill (region-beginning) (region-end))
  (evil-delete-char (region-beginning) (region-end))
  (winum-select-window-by-number 1)
  (evil-open-below 1)
  (yank)
  (evil-append-line 0)
  (insert " -> ")
  )
(global-set-key (kbd "<f1>") 'shdennlin/str)
(defun shdennlin/str2 ()
  (interactive)
  (copy-region-as-kill (region-beginning) (region-end))
  (winum-select-window-by-number 2)
  (yank)
  )
(global-set-key (kbd "<f2>") 'shdennlin/str2)
